### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by antoine-mouchamps** [antoine-mouchamps/pyfigure98#6]
Dans addFigure(), "col should thus be equal" devrait être "cols should ..."

**Comment by timotheeMM** [comment]
Hello @antoine-mouchamps,
I would like to solve your issue, but I can not find the file where to fix the error?
Could you be more specific?
Thank you in advance.

**Comment by antoine-mouchamps** [comment]
Hello @timotheeMM,
The file containing this method and its description is located in src/pyfigure98/Figure/_set_figure.py.
The documentation of my package (as well as its functionnalities) are far from being complete, I have just learned how to publish it today so sorry if its organisation is confusing. I am open to advice if you have some.

**Comment by timotheeMM** [comment]
It's okay!
